var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(a){return a.raw=a};$jscomp.createTemplateTagFirstArgWithRaw=function(a,b){a.raw=b;return a};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
$jscomp.arrayFromIterator=function(a){for(var b,d=[];!(b=a.next()).done;)d.push(b.value);return d};$jscomp.arrayFromIterable=function(a){return a instanceof Array?a:$jscomp.arrayFromIterator($jscomp.makeIterator(a))};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,d){if(a==Array.prototype||a==Object.prototype)return a;a[b]=d.value;return a};$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var d=a[b];if(d&&d.Math==Math)return d}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var d=$jscomp.propertyToPolyfillSymbol[b];if(null==d)return a[b];d=a[d];return void 0!==d?d:a[b]};
$jscomp.polyfill=function(a,b,d,l){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,d,l):$jscomp.polyfillUnisolated(a,b,d,l))};$jscomp.polyfillUnisolated=function(a,b,d,l){d=$jscomp.global;a=a.split(".");for(l=0;l<a.length-1;l++){var h=a[l];if(!(h in d))return;d=d[h]}a=a[a.length-1];l=d[a];b=b(l);b!=l&&null!=b&&$jscomp.defineProperty(d,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,d,l){var h=a.split(".");a=1===h.length;l=h[0];l=!a&&l in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var r=0;r<h.length-1;r++){var p=h[r];if(!(p in l))return;l=l[p]}h=h[h.length-1];d=$jscomp.IS_SYMBOL_NATIVE&&"es6"===d?l[h]:null;b=b(d);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,h,{configurable:!0,writable:!0,value:b}):b!==d&&(void 0===$jscomp.propertyToPolyfillSymbol[h]&&(d=1E9*Math.random()>>>0,$jscomp.propertyToPolyfillSymbol[h]=$jscomp.IS_SYMBOL_NATIVE?
$jscomp.global.Symbol(h):$jscomp.POLYFILL_PREFIX+d+"$"+h),$jscomp.defineProperty(l,$jscomp.propertyToPolyfillSymbol[h],{configurable:!0,writable:!0,value:b})))};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(d){}return!1};
$jscomp.setPrototypeOf=$jscomp.TRUST_ES6_POLYFILLS&&"function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;$jscomp.generator={};$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};
$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};
$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype["return"]=function(a){this.abruptCompletion_={"return":a};this.nextAddress=this.finallyAddress_};
$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(a,b){this.nextAddress=b;return{value:a}};$jscomp.generator.Context.prototype.yieldAll=function(a,b){var d=$jscomp.makeIterator(a),l=d.next();$jscomp.generator.ensureIteratorResultIsObject_(l);if(l.done)this.yieldResult=l.value,this.nextAddress=b;else return this.yieldAllIterator_=d,this.yield(l.value,b)};
$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,b){this.catchAddress_=a;void 0!=b&&(this.finallyAddress_=b)};$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(a,b){this.nextAddress=a;this.catchAddress_=b||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,b,d){d?this.finallyContexts_[d]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=b||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,b){var d=this.finallyContexts_.splice(b||0)[0];if(d=this.abruptCompletion_=this.abruptCompletion_||d){if(d.isException)return this.jumpToErrorHandler_();void 0!=d.jumpTo&&this.finallyAddress_<d.jumpTo?(this.nextAddress=d.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};
$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var b in a)this.properties_.push(b);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var b=this.context_.yieldAllIterator_;if(b)return this.yieldAllStep_("return"in b?b["return"]:function(d){return{value:d,done:!0}},a,this.context_["return"]);this.context_["return"](a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,b,d){try{var l=a.call(this.context_.yieldAllIterator_,b);$jscomp.generator.ensureIteratorResultIsObject_(l);if(!l.done)return this.context_.stop_(),l;var h=l.value}catch(r){return this.context_.yieldAllIterator_=null,this.context_.throw_(r),this.nextStep_()}this.context_.yieldAllIterator_=null;d.call(this.context_,h);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(b){this.context_.yieldResult=void 0,this.context_.throw_(b)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a["return"],done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(b){return a.next_(b)};this["throw"]=function(b){return a.throw_(b)};this["return"]=function(b){return a.return_(b)};this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,b){var d=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(b));$jscomp.setPrototypeOf&&a.prototype&&$jscomp.setPrototypeOf(d,a.prototype);return d};
$jscomp.asyncExecutePromiseGenerator=function(a){function b(l){return a.next(l)}function d(l){return a["throw"](l)}return new Promise(function(l,h){function r(p){p.done?l(p.value):Promise.resolve(p.value).then(b,d).then(r,h)}r(a.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(a){return $jscomp.asyncExecutePromiseGenerator(a())};$jscomp.asyncExecutePromiseGeneratorProgram=function(a){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(a)))};
var width=window.innerWidth,height=window.innerHeight,points=[];
function main(){function a(){v?(v=!1,D.style.visibility="visible",m.visible=!1):(v=!0,D.style.visibility="hidden",m.visible=!0)}function b(c){c.target.remove()}function d(c){var k=c.x,f=c.y;c=c.z+.5;var n=2*Math.tan(E/2)*(2-(1-c-.5)),e=n*z,g=new THREE.Vector3;g.set((k-.5)*e,n*(1-f-.5),1-c-.5);return g}function l(c){if(points&&points[0]&&m){c=d(points[23]);var k=d(points[24]),f=d(points[11]),n=d(points[12]),e=f.clone().add(n).multiplyScalar(.5),g=c.clone().add(k).multiplyScalar(.5);e=e.clone().sub(g).multiplyScalar(.1);
e=g.clone().add(e);g=m.children[1].skeleton.bones[0];e=e.clone();g.parent.worldToLocal(e);m.children[1].skeleton.bones[0].position.copy(e);e=d(points[13]);var q=d(points[15]);g=f.clone().sub(e);e=q.clone().sub(e);g=g.clone().cross(e);g.normalize();e=m.children[1].skeleton.bones[8];q=m.children[1].skeleton.bones[9];m.children[1].skeleton.bones[7].up=g;e.up=g;q.up=g;e=d(points[14]);q=d(points[16]);g=n.clone().sub(e);e=q.clone().sub(e);g=g.clone().cross(e);g.normalize().multiplyScalar(-1);e=m.children[1].skeleton.bones[32];
q=m.children[1].skeleton.bones[33];m.children[1].skeleton.bones[31].up=g;e.up=g;q.up=g;e=d(points[26]);q=d(points[28]);g=k.clone().sub(e);e=q.clone().sub(e);g=g.clone().cross(e);g.normalize().multiplyScalar(1);e=m.children[1].skeleton.bones[61];m.children[1].skeleton.bones[60].up=g;e.up=g;e=d(points[25]);q=d(points[27]);g=c.clone().sub(e);e=q.clone().sub(e);g=g.clone().cross(e);g.normalize().multiplyScalar(1);e=m.children[1].skeleton.bones[56];m.children[1].skeleton.bones[55].up=g;e.up=g;g=c.clone().sub(k);
f=f.clone().add(n).multiplyScalar(.5);k=c.clone().add(k).multiplyScalar(.5);c=f.clone().add(k).multiplyScalar(.5);k=f.clone().sub(k);f=g.clone().cross(k);f.normalize();n=m.children[1].skeleton.bones[0];n.up=k;n.lookAt(c.clone().add(f));n.rotateX(Math.PI/10);c=k.length()/A/95;k=new THREE.Vector3;k.setScalar(c);m.scale.copy(k);for(c=0;14>c;c++){k=J[c];e=points[K[c]];f=m.children[1].skeleton.bones[k];n=e.x;g=e.y;q=e.z+.5;var F=2*Math.tan(E/2)*(2-(1-q-.5)),L=F*z;e=new THREE.Vector3;e.set((n-.5)*L,F*(1-
g-.5),1-q-.5);[56,57,61,62,9,10,33,34].includes(k)&&(f=f.parent,f.lookAt(e),f.rotateX(Math.PI/2),[61,62,56,57].includes(k)&&f.rotateY(Math.PI/2));m.updateMatrixWorld()}}r.render(x,w);requestAnimationFrame(l)}var h=document.getElementById("c"),r=new THREE.WebGLRenderer({canvas:h,antialias:!0,alpha:!0}),p=document.documentElement.clientWidth,u=document.documentElement.clientHeight;console.log(p,u);r.setSize(p,u);r.setClearColor(16777215,0);var x=new THREE.Scene,z=window.innerWidth/window.innerHeight,
w=new THREE.PerspectiveCamera(75,z,.01,2E3);w.position.z=2;var E=w.fov*Math.PI/180,G=document.getElementById("loading-screen"),B=document.getElementsByClassName("input-video")[0],v=!1,D=document.getElementsByClassName("outline")[0];h=navigator.userAgent.toLowerCase();console.log("android",h,h.indexOf("android"));var H=!1;-1<h.indexOf("android")?H=!0:B.classList.add("desktop-window");var I=!0,t=[],y=new Pose({locateFile:function(c){return"https://cdn.jsdelivr.net/npm/@mediapipe/pose@0.3.1620246326/"+
c}});y.setOptions({selfieMode:!0,upperBodyOnly:!1,smoothLandmarks:!0,minDetectionConfidence:.5,minTrackingConfidence:.5});y.onResults(function(c){if(c.poseLandmarks){v||a();if(5>t.length)t.push(c.poseLandmarks);else{var k=t.slice(1);k.push(c.poseLandmarks);t=k}c=[].concat($jscomp.arrayFromIterable(t[0]));k=t.length;if(1<k)for(var f=0;f<c.length;f++){for(var n=1;n<k;n++)c[f].x+=t[n][f].x,c[f].y+=t[n][f].y,c[f].z+=t[n][f].z;c[f].x/=k;c[f].y/=k;c[f].z/=k}points=c;I&&(I=!1,console.log(points))}else v&&
a()});console.log(function(c){var k=new Set,f=c;do Object.getOwnPropertyNames(f).map(function(n){return k.add(n)});while(f=Object.getPrototypeOf(f));return[].concat($jscomp.arrayFromIterable(k.keys())).filter(function(n){return"function"===typeof c[n]})}(y));h=new Camera(B,{onFrame:function(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(c){return c.yield(y.send({image:B}),0)})},width:Math.max(u,p),height:Math.min(u,p)});console.log("camera",h);h.start();window.addEventListener("resize",
function(){w.aspect=window.innerWidth/window.innerHeight;w.updateProjectionMatrix();p=document.documentElement.clientWidth;u=document.documentElement.clientHeight;r.setSize(p,u);if(H&&medStream){var c=medStream.getVideoTracks()[0].getConstraints();c.width=Math.max(u,p);c.height=Math.min(u,p);medStream.getVideoTracks()[0].applyConstraints(c)}},!1);new THREE.MeshBasicMaterial({color:"green",skinning:!0});new THREE.MeshBasicMaterial({color:"red",skinning:!0});new THREE.MeshBasicMaterial({color:"red",
skinning:!0});var m,A;h=new THREE.LoadingManager;var M=document.getElementById("progress");h.onProgress=function(c,k,f){console.log(c,k,f);M.innerHTML="Loaded "+(k/f*100).toFixed(2)+"%"};h.onLoad=function(){console.log("fade out");G.classList.add("fade-out");G.addEventListener("transitionend",b)};var C=new THREE.TextureLoader(h);texture_diffuse=C.load("textures/diffuse.png",function(c){});texture_diffuse.flipY=!1;texture_normal=C.load("textures/normal.png",function(c){});texture_normal.flipY=!1;texture_roughness=
C.load("textures/roughness.png",function(c){});texture_roughness.flipY=!1;(new THREE.GLTFLoader(h)).load("mann_no_mats.glb",function(c){console.log("loading mann");console.log(c.scene.children[2].children[1].material);m=c.scene.children[2];c=m.children[1].material;c.map=texture_diffuse;c.roughnessMap=texture_roughness;c.normalMap=texture_normal;c.metalness=.5;c.roughness=2;console.log(m);x.add(m);m.visible=!1;m.position.set(0,-1,0);m.rotateX(Math.PI/20);m.updateMatrix();m.updateMatrixWorld();var k=
m.children[1].skeleton.bones[7],f=m.children[1].skeleton.bones[31];c=m.children[1].skeleton.bones[60];var n=m.children[1].skeleton.bones[55],e=new THREE.Vector3,g=new THREE.Vector3;f.getWorldPosition(e);k.getWorldPosition(g);k=new THREE.Vector3;k.copy(e).add(g).multiplyScalar(.5);e=new THREE.Vector3;g=new THREE.Vector3;c.getWorldPosition(e);n.getWorldPosition(g);c=new THREE.Vector3;c.copy(e).add(g).multiplyScalar(.5);A=k.clone().sub(c).length();console.log(A)},function(c){console.log(c.loaded/c.total*
100+"% loaded")},function(c){console.log("An error happened")});h=new THREE.AmbientLight(16777215,2);x.add(h);h=new THREE.DirectionalLight(16777215,.1);h.position.set(0,0,-2);x.add(h);var J=[8,9,10,32,33,34,55,56,57,60,61,62,58,63],K=[11,13,15,12,14,16,23,25,27,24,26,28,31,32];requestAnimationFrame(l)}window.onload=main;